[SIW-1067] Move static assets out of app directory
pagopa/io-web-profile pull request #149
Opened 2024-04-25 12:26 UTC by gunzip

## Short description

Move static assets out of app directory.

## List of changes proposed in this pull request

Ditto.

## How to test

yarn build

2024-04-29 13:27 UTC, Ladirico commented
Sorry but is not clear to me from the description why there was a need to make this change, and I think 'Ditto' as 'list of changes' is a mistake. We use this template to keep track of the choices made and describe what is done in the PR.

2024-04-29 13:37 UTC, gunzip commented
The best practice with nextjs is to put all static assets into the public directory https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets

There's no reason to have static assets both under public and under app, locations which nextjs might threat differently.

In the context of this or, the list of changes are the same shared into the description. if you want the author to add a reason, you may want to change the pull request template with an appropriate title, which is indeed a good idea!

2024-04-29 15:36 UTC, Ladirico requested changes

2024-04-29 15:36 UTC, Ladirico commented on src/app/favicon.ico
Why has this icon been removed? This here is the icon that is used in the site tab, if it is not there nothing is displayed and it is wrong.

2024-04-29 16:25 UTC, gunzip commented on src/app/favicon.ico
It's removed since there's another identical one in the public folder.

2024-04-29 16:26 UTC, gunzip commented
What I meant was that "description" and "list of changes" are overlapping concept, so if we want the reason for the changes we should update one tile to something like "reason for this changes".

2024-04-29 22:50 UTC, Ladirico commented on src/app/favicon.ico
Yes, but in this case it is wrong to delete the favicon because the tab is not displayed, as the [documentation of next.js](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#image-files-ico-jpg-png) says the favicon is automatically inserted as an app icon only if it is at the height of `/app`

2024-04-29 22:54 UTC, Ladirico commented
> What I meant was that "description" and "list of changes" are overlapping concepts, so if we want the reason for the changes we should update one title to something like "reason for this changes".

Yes! It's a good idea!

2024-04-30 08:02 UTC, gunzip commented
You're right! I'm closing this PR according to docs.

2024-04-30 08:02 UTC, closed without merging