[IOPID-1557] : Email Confirmation
pagopa/io-web-profile pull request #154
Opened 2024-05-21 08:58 UTC by ClaudioNTT

## Short description

This pull request aims to implement the email-validation page within the io web profile project, as outlined in the JIRA task.

## List of changes proposed in this pull request

- Added EmailValidationApiClient
- Added Email Confirmation page
- Modified session provider and layout to accommodate pages without header and footer (in this case).

## How to test
- To enable the email validation page, set the env variable **NEXT_PUBLIC_VALIDATION_EMAIL** to **true** 
- Set up the mock API using Mockoon for the io function.
- Access the io web profile home page and verify functionality.
- Enable Mockoon with the new mock (stored in the mock folder).
- Access the email confirmation page using the provided token in the query parameter and verify API calls according to OpenAPI specifications.

Example URL: http://localhost:3000/it/conferma-email/?token=05QSY3JXN8XF47LTKRW9EMHZBX:179aeae8dcc01abdab31e5ba

# The KO pages and the management of the various errors will be introduced in the next PR since they are on other Jira tasks.

Video:

[Video](https://github.com/pagopa/io-web-profile/assets/145718190/8d2c8876-5b8f-49d9-bb76-2c09d97509b1)

2024-05-23 07:54 UTC, Ladirico requested changes

2024-05-23 07:54 UTC, Ladirico commented on src/api/emailValidationApiClient.ts
> +const useFetch = () => {
It it might be better to call it useFetchEmailValidation or a similar name to differentiate it from the existing useFetch hook

2024-05-23 07:54 UTC, Ladirico commented on src/app/[locale]/(pages)/conferma-email/page.tsx
> +  }, [isLoading]);
I think you can delete this console.log (and this useeffect too)

2024-05-23 07:56 UTC, Ladirico commented
Could you add to the PR description the screen recording of what was done in this PR? 
cc: @ClaudioNTT

2024-05-28 12:44 UTC, Ladirico commented
I noticed that there are differences between the [figma](https://www.figma.com/design/BEXvjQmBkMRRFiNcMgE8g3/Login-Veloce?node-id=6406-55717&t=JIaWblMajokEytaF-4) and what you have realised. In the mobile view the texts are not centred vertically and the background is grey (in figma it is white) 
![Uploading Screenshot 2024-05-28 alle 14.43.57.png…]()

2024-05-29 07:53 UTC, arcogabbo commented on openApi/external.yaml
after https://github.com/pagopa/io-web-profile/pull/154/commits/5163c5c3b6929c4db85e7667b6c25502a9bae55a, I think this file can be removed entirely

2024-05-29 15:27 UTC, Ladirico requested changes

2024-06-03 07:59 UTC, Ladirico approved these changes
LGTM! 🚀

2024-06-04 07:16 UTC, merged