[SIW-1201] add wallet test
pagopa/io-web-profile pull request #160
Opened 2024-06-10 08:20 UTC by PierpaoloPirasSp

## WALLET TESTING

Tests have been added for the WALLET section.

## List of Implemented Tests

1. ### Accordion Component
   The accordion component has been reimplemented to track the opening and closing of the accordions themselves, and the relevant test has been added.
2. ### Wallet Revocation Error
   Tests for the displayed copy and the buttons present on the error page during wallet deactivation.
3. ### Wallet Thank You Page
   Tests for the displayed copy and the buttons present on the success page during wallet deactivation.
4. ### getWalletStatus
   Test for the getWalletStatus utility, which is used to track the status of the wallet in mix panel events.
5. ### ProfileCards
   Test for the ProfileCards component to verify that the wallet deactivation card is displayed only when the wallet is active.
6. ### HomeWalletCard
   Test for the HomeWalletCard component to verify that the card is displayed with the correct copy based on the wallet status.

2024-06-19 16:31 UTC, gunzip commented
@PierpaoloPirasSp it looks like there are conflicts and we cannot merge this until they're solved

2024-06-20 07:05 UTC, PierpaoloPirasSp commented
@gunzip Conflicts are resolved

2024-06-24 11:56 UTC, gunzip requested changes

2024-06-24 11:56 UTC, gunzip commented on openApi/openapi.yaml
> +          text/plain:
please revert to the previous version of this openapi spec (moreover, this is invalid synatx)

see https://github.com/pagopa/io-wallet/blob/master/apps/io-wallet-web-func/openapi.yaml#L45

2024-06-24 11:56 UTC, gunzip commented on openApi/openapi.yaml
> +          - id
ditto, revert to previous working version

2024-06-24 11:56 UTC, gunzip commented on src/api/webProfileApiClient.ts
> +  setWalletInstanceStatus: async (id: string) => {
revert to previous version

2024-06-24 11:56 UTC, gunzip commented on src/app/[locale]/(pages)/revoca-wallet/errore/__test__/errorPage.test.tsx
> +import { renderWithProviders } from "@/app/[locale]/_utils/test-utils";
use dashes for file names, ie. `error-page.test.tsx`

2024-06-24 11:56 UTC, gunzip commented on src/app/[locale]/(pages)/revoca-wallet/operazione-completata/__test__/thankYouPage.test.tsx
> +  test('should render error page', async () => {
```suggestion
  test('should render thank you page', async () => {
```

2024-06-24 11:56 UTC, gunzip commented on src/app/[locale]/_component/homeWalletCard/__test__/homeWalletCard.test.tsx
> +import React from 'react';
`home-wallet-card.test.tsx`

2024-06-24 11:56 UTC, gunzip commented on src/app/[locale]/_component/profileCards/__test__/profileCards.test.tsx
> +import React from 'react';
`profile-cards.test.tsx`

2024-06-24 11:56 UTC, gunzip commented on src/app/[locale]/_component/profileCards/__test__/profileCards.test.tsx
> +    const disbaleTitle = screen.getAllByText(it.itwallet.common.disablewallet)
```suggestion
    const disableTitle = screen.getAllByText(it.itwallet.common.disablewallet)
```

2024-06-26 21:43 UTC, gunzip approved these changes

2024-06-26 21:43 UTC, merged